import { Permission } from '@/shared/types/permissions';
import { PERMISSIONS } from './permissions';

export const ADMIN_PERMISSIONS: Permission[] = [
  // User Permissions
  PERMISSIONS.USERS_READ_ANY,
  PERMISSIONS.USERS_READ_SELF,
  PERMISSIONS.USERS_CREATE_ADMIN,
  PERMISSIONS.USERS_CREATE_ADVERTISER,
  PERMISSIONS.USERS_UPDATE_SELF,
  PERMISSIONS.USERS_DELETE_ANY,

  // advertiser profile
  PERMISSIONS.READ_ADVERTISER_PROFILE_ANY,

  // Dashboard Permissions
  PERMISSIONS.DASHBOARD_ACCESS_ADMIN,

  // Billboard Permissions
  PERMISSIONS.BILLBOARDS_READ,
  PERMISSIONS.BILLBOARDS_CREATE,
  PERMISSIONS.BILLBOARDS_UPDATE,
  PERMISSIONS.BILLBOARDS_DELETE,

  // Ad Creative Permissions (admins moderate all)
  PERMISSIONS.CREATIVES_READ_ANY,

  // Playlist Permissions (admins program digital screens)
  PERMISSIONS.PLAYLISTS_READ,
  PERMISSIONS.PLAYLISTS_CREATE,
  PERMISSIONS.PLAYLISTS_UPDATE,
  PERMISSIONS.PLAYLISTS_DELETE,

  // Schedule Permissions (admins book playlists onto screens)
  PERMISSIONS.SCHEDULES_READ,
  PERMISSIONS.SCHEDULES_CREATE,
  PERMISSIONS.SCHEDULES_UPDATE,
  PERMISSIONS.SCHEDULES_DELETE,

  // Impression Permissions (admins read playback analytics)
  PERMISSIONS.IMPRESSIONS_READ,

  // Booking Permissions (admins review and moderate reservations)
  PERMISSIONS.BOOKINGS_READ,
  PERMISSIONS.BOOKINGS_MODERATE,

  // Campaign Permissions
  PERMISSIONS.CAMPAIGNS_READ_ANY,
];
